// flow-typed signature: be99213045ee5bed1657c40d8b965ec2
// flow-typed version: <<STUB>>/doctrine-temporary-fork_v^2.0.0-alpha-allowarrayindex/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'doctrine-temporary-fork'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'doctrine-temporary-fork' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'doctrine-temporary-fork/lib/doctrine' {
  declare module.exports: any;
}

declare module 'doctrine-temporary-fork/lib/typed' {
  declare module.exports: any;
}

declare module 'doctrine-temporary-fork/lib/utility' {
  declare module.exports: any;
}

// Filename aliases
declare module 'doctrine-temporary-fork/lib/doctrine.js' {
  declare module.exports: $Exports<'doctrine-temporary-fork/lib/doctrine'>;
}
declare module 'doctrine-temporary-fork/lib/typed.js' {
  declare module.exports: $Exports<'doctrine-temporary-fork/lib/typed'>;
}
declare module 'doctrine-temporary-fork/lib/utility.js' {
  declare module.exports: $Exports<'doctrine-temporary-fork/lib/utility'>;
}
