// flow-typed signature: 49a552b7d2514a2d55d24db80c5f2a68
// flow-typed version: <<STUB>>/ganache-cli_v6.0.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ganache-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ganache-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ganache-cli/build/cli.node' {
  declare module.exports: any;
}

declare module 'ganache-cli/build/lib.node' {
  declare module.exports: any;
}

declare module 'ganache-cli/build/provider.node' {
  declare module.exports: any;
}

declare module 'ganache-cli/build/server.node' {
  declare module.exports: any;
}

declare module 'ganache-cli/cli' {
  declare module.exports: any;
}

declare module 'ganache-cli/lib' {
  declare module.exports: any;
}

declare module 'ganache-cli/nil' {
  declare module.exports: any;
}

declare module 'ganache-cli/perf/transactions' {
  declare module.exports: any;
}

declare module 'ganache-cli/webpack/cli.webpack.config' {
  declare module.exports: any;
}

declare module 'ganache-cli/webpack/lib.webpack.config' {
  declare module.exports: any;
}

declare module 'ganache-cli/webpack/provider.webpack.config' {
  declare module.exports: any;
}

declare module 'ganache-cli/webpack/server.webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ganache-cli/build/cli.node.js' {
  declare module.exports: $Exports<'ganache-cli/build/cli.node'>;
}
declare module 'ganache-cli/build/lib.node.js' {
  declare module.exports: $Exports<'ganache-cli/build/lib.node'>;
}
declare module 'ganache-cli/build/provider.node.js' {
  declare module.exports: $Exports<'ganache-cli/build/provider.node'>;
}
declare module 'ganache-cli/build/server.node.js' {
  declare module.exports: $Exports<'ganache-cli/build/server.node'>;
}
declare module 'ganache-cli/cli.js' {
  declare module.exports: $Exports<'ganache-cli/cli'>;
}
declare module 'ganache-cli/lib.js' {
  declare module.exports: $Exports<'ganache-cli/lib'>;
}
declare module 'ganache-cli/nil.js' {
  declare module.exports: $Exports<'ganache-cli/nil'>;
}
declare module 'ganache-cli/perf/transactions.js' {
  declare module.exports: $Exports<'ganache-cli/perf/transactions'>;
}
declare module 'ganache-cli/webpack/cli.webpack.config.js' {
  declare module.exports: $Exports<'ganache-cli/webpack/cli.webpack.config'>;
}
declare module 'ganache-cli/webpack/lib.webpack.config.js' {
  declare module.exports: $Exports<'ganache-cli/webpack/lib.webpack.config'>;
}
declare module 'ganache-cli/webpack/provider.webpack.config.js' {
  declare module.exports: $Exports<'ganache-cli/webpack/provider.webpack.config'>;
}
declare module 'ganache-cli/webpack/server.webpack.config.js' {
  declare module.exports: $Exports<'ganache-cli/webpack/server.webpack.config'>;
}
