// flow-typed signature: 8bddda9809c4a476f046e1666c1e1a91
// flow-typed version: <<STUB>>/globals-docs_v^2.4.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globals-docs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'globals-docs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'globals-docs/scripts/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'globals-docs/index' {
  declare module.exports: $Exports<'globals-docs'>;
}
declare module 'globals-docs/index.js' {
  declare module.exports: $Exports<'globals-docs'>;
}
declare module 'globals-docs/scripts/build.js' {
  declare module.exports: $Exports<'globals-docs/scripts/build'>;
}
