// flow-typed signature: 3383ef0d04f7c03c032fffc8a2ec08d7
// flow-typed version: <<STUB>>/truffle_v4.0.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle/build/chain.bundled' {
  declare module.exports: any;
}

declare module 'truffle/build/cli.bundled' {
  declare module.exports: any;
}

declare module 'truffle/build/templates/example' {
  declare module.exports: any;
}

declare module 'truffle/build/templates/migration' {
  declare module.exports: any;
}

declare module 'truffle/cli.webpack.config' {
  declare module.exports: any;
}

declare module 'truffle/nil' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commandrunner' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/contract_names/test_imports' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/cyclic_dependencies/compiles' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/happy_path/happypath' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/memorylogger' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/parameters' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/reporter' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/server' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/solidity_testing/with_balances' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle/build/chain.bundled.js' {
  declare module.exports: $Exports<'truffle/build/chain.bundled'>;
}
declare module 'truffle/build/cli.bundled.js' {
  declare module.exports: $Exports<'truffle/build/cli.bundled'>;
}
declare module 'truffle/build/templates/example.js' {
  declare module.exports: $Exports<'truffle/build/templates/example'>;
}
declare module 'truffle/build/templates/migration.js' {
  declare module.exports: $Exports<'truffle/build/templates/migration'>;
}
declare module 'truffle/cli.webpack.config.js' {
  declare module.exports: $Exports<'truffle/cli.webpack.config'>;
}
declare module 'truffle/nil.js' {
  declare module.exports: $Exports<'truffle/nil'>;
}
declare module 'truffle/test/scenarios.js' {
  declare module.exports: $Exports<'truffle/test/scenarios'>;
}
declare module 'truffle/test/scenarios/commandrunner.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commandrunner'>;
}
declare module 'truffle/test/scenarios/contract_names/test_imports.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/contract_names/test_imports'>;
}
declare module 'truffle/test/scenarios/cyclic_dependencies/compiles.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/cyclic_dependencies/compiles'>;
}
declare module 'truffle/test/scenarios/happy_path/happypath.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/happy_path/happypath'>;
}
declare module 'truffle/test/scenarios/memorylogger.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/memorylogger'>;
}
declare module 'truffle/test/scenarios/migrations/parameters.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/parameters'>;
}
declare module 'truffle/test/scenarios/reporter.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/reporter'>;
}
declare module 'truffle/test/scenarios/server.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/server'>;
}
declare module 'truffle/test/scenarios/solidity_testing/with_balances.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/solidity_testing/with_balances'>;
}
