// flow-typed signature: 07ef7ffd57c92dea27924fec5acf482d
// flow-typed version: <<STUB>>/truffle-contract_v3.0.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle-contract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle-contract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle-contract/contract' {
  declare module.exports: any;
}

declare module 'truffle-contract/dist/truffle-contract' {
  declare module.exports: any;
}

declare module 'truffle-contract/dist/truffle-contract.min' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/abstractions' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/cloning' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/customoptions' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/deprecated_keys' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/lib/MetaCoin.sol' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/linking' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/networks' {
  declare module.exports: any;
}

declare module 'truffle-contract/test/upgrade' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle-contract/contract.js' {
  declare module.exports: $Exports<'truffle-contract/contract'>;
}
declare module 'truffle-contract/dist/truffle-contract.js' {
  declare module.exports: $Exports<'truffle-contract/dist/truffle-contract'>;
}
declare module 'truffle-contract/dist/truffle-contract.min.js' {
  declare module.exports: $Exports<'truffle-contract/dist/truffle-contract.min'>;
}
declare module 'truffle-contract/index' {
  declare module.exports: $Exports<'truffle-contract'>;
}
declare module 'truffle-contract/index.js' {
  declare module.exports: $Exports<'truffle-contract'>;
}
declare module 'truffle-contract/test/abstractions.js' {
  declare module.exports: $Exports<'truffle-contract/test/abstractions'>;
}
declare module 'truffle-contract/test/cloning.js' {
  declare module.exports: $Exports<'truffle-contract/test/cloning'>;
}
declare module 'truffle-contract/test/customoptions.js' {
  declare module.exports: $Exports<'truffle-contract/test/customoptions'>;
}
declare module 'truffle-contract/test/deprecated_keys.js' {
  declare module.exports: $Exports<'truffle-contract/test/deprecated_keys'>;
}
declare module 'truffle-contract/test/lib/MetaCoin.sol.js' {
  declare module.exports: $Exports<'truffle-contract/test/lib/MetaCoin.sol'>;
}
declare module 'truffle-contract/test/linking.js' {
  declare module.exports: $Exports<'truffle-contract/test/linking'>;
}
declare module 'truffle-contract/test/networks.js' {
  declare module.exports: $Exports<'truffle-contract/test/networks'>;
}
declare module 'truffle-contract/test/upgrade.js' {
  declare module.exports: $Exports<'truffle-contract/test/upgrade'>;
}
