// flow-typed signature: 47c6539f00d6842fa690e81d2ba1b3a9
// flow-typed version: <<STUB>>/unist-builder_v^1.0.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unist-builder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unist-builder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'unist-builder/index' {
  declare module.exports: $Exports<'unist-builder'>;
}
declare module 'unist-builder/index.js' {
  declare module.exports: $Exports<'unist-builder'>;
}
