// flow-typed signature: 4444431b513a8e609c4b478ac283fb94
// flow-typed version: <<STUB>>/@0xproject/web3-wrapper_v0.1.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@0xproject/web3-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@0xproject/web3-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@0xproject/web3-wrapper/lib/index' {
  declare module.exports: any;
}

declare module '@0xproject/web3-wrapper/scripts/postpublish' {
  declare module.exports: any;
}

// Filename aliases
declare module '@0xproject/web3-wrapper/lib/index.js' {
  declare module.exports: $Exports<'@0xproject/web3-wrapper/lib/index'>;
}
declare module '@0xproject/web3-wrapper/scripts/postpublish.js' {
  declare module.exports: $Exports<'@0xproject/web3-wrapper/scripts/postpublish'>;
}
